version: '3.8'

services:
  app:
    build: .
    container_name: api_web_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=techapi_db
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: api_web_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: techapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
