sonar.projectKey=draco-tech-reparaciones
sonar.projectName=Draco Tech Reparaciones
sonar.projectVersion=1.0.0

# Authentication
sonar.token=sqa_6291b687d2172819f5dc532e5a34945b6ada08b5

# Host URL
sonar.host.url=http://172.19.0.3:9000

# Path to the source directories
sonar.sources=.

# Exclusions
sonar.exclusions=node_modules/**, k8s/**, terraform/**, argocd/**, coverage/**

# Test files
# sonar.tests=tests
# sonar.test.inclusions=**/*.test.js, **/*.spec.js

# Encoding of the source code
sonar.sourceEncoding=UTF-8
