apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: cide-app
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/blocks
        wal:
          path: /var/tempo/wal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: cide-app
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.0
          args:
            - "-config.file=/etc/tempo.yaml"
          ports:
            - containerPort: 3200
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: tempo-config-vol
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: tempo-config-vol
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: cide-app
spec:
  selector:
    app: tempo
  ports:
    - name: http-tempo
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
